name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Можно использовать windows-latest или macos-latest для других операционных систем

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Запуск на нескольких ОС

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Укажите вашу версию Java
          distribution: 'temurin'

      # Шаг 3: Компиляция исходного кода
      - name: Compile Java code
        run: |
          javac -d bin src/**/*.java  # Компилируем все исходники в папке src в папку bin

      # Шаг 4: Компиляция тестов и запуск с JUnit 5
      - name: Run tests
        run: |
          javac -cp lib/junit-jupiter-api-5.11.4.jar:lib/junit-jupiter-engine-5.11.4.jar:lib/hamcrest-core-1.3.jar -d bin/test src/test/**/*.java  # Компиляция тестов
          java -cp lib/junit-jupiter-api-5.11.4.jar:lib/junit-jupiter-engine-5.11.4.jar:lib/hamcrest-core-1.3.jar org.junit.jupiter.api.Test src/test/MainTest  # Запуск тестов
