name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
# Задача для тестирования проекта
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'  # Укажите нужную версию JDK
          distribution: 'temurin'

      # Шаг 3: Установка Maven
      - name: Set up Maven
        run: |
          wget https://dlcdn.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
          tar -xvzf apache-maven-3.8.1-bin.tar.gz
          sudo mv apache-maven-3.8.1 /opt/maven
          sudo ln -s /opt/maven/bin/mvn /usr/local/bin/mvn

      # Шаг 4: Собираем проект с помощью Maven
      - name: Build with Maven
        run: mvn clean install -DskipTests=true  # Не запускаем тесты на этапе сборки

      # Шаг 5: Запуск тестов с помощью Maven
      - name: Run tests with Maven
        run: mvn test

      # Шаг 6: Архивируем артефакты (если нужно)
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: calculator-artifact
          path: target/calculator-1.0-SNAPSHOT.jar
